// Esquema do banco (PostgreSQL). É idempotente: roda a cada cold start e só cria o que ainda não existe.
// Para evoluir o banco no futuro, acrescente aqui `ALTER TABLE ... ADD COLUMN IF NOT EXISTS ...`.
//
// Datas ficam como TEXT ('2026-10-09') de propósito: o app trabalha com o "dia" do usuário,
// sem fuso horário, e assim a API devolve exatamente o que o front espera.
export const SCHEMA = `
CREATE TABLE IF NOT EXISTS users(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  hash TEXT NOT NULL,
  terms_version TEXT,
  terms_accepted_at TEXT,
  email_verified_at TEXT,
  created_at TEXT,
  last_login_at TEXT,
  token_valid_after BIGINT
);

CREATE TABLE IF NOT EXISTS habits(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  "time" TEXT,
  weekdays TEXT NOT NULL DEFAULT '',
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS habit_logs(
  habit_id INTEGER NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  PRIMARY KEY(habit_id, date)
);

CREATE TABLE IF NOT EXISTS tasks(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT DEFAULT 'Geral',
  status TEXT NOT NULL DEFAULT 'NAO_INICIADA',
  started_at TEXT,
  finished_at TEXT,
  due_date TEXT
);

CREATE TABLE IF NOT EXISTS checkins(
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  tags TEXT NOT NULL DEFAULT '[]',
  notes TEXT,
  PRIMARY KEY(user_id, date)
);

CREATE TABLE IF NOT EXISTS workout_exercises(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  weekday INTEGER NOT NULL,
  name TEXT NOT NULL,
  sets INTEGER NOT NULL DEFAULT 3,
  obs TEXT
);

CREATE TABLE IF NOT EXISTS sessions(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  label TEXT,
  started_at TEXT,
  finished_at TEXT,
  duration_sec INTEGER
);

CREATE TABLE IF NOT EXISTS session_sets(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  exercise TEXT NOT NULL,
  set_number INTEGER NOT NULL,
  reps INTEGER NOT NULL,
  load_kg DOUBLE PRECISION NOT NULL
);

-- limite de tentativas de login/senha. Fica no banco porque no Vercel cada requisição pode cair em uma instância diferente.
CREATE TABLE IF NOT EXISTS rate_limits(
  key TEXT PRIMARY KEY,
  n INTEGER NOT NULL,
  window_start BIGINT NOT NULL
);

-- Segurança: no Supabase, tabelas do schema public ficam acessíveis pela API pública (REST) com a chave anon.
-- Ligar o RLS sem criar nenhuma policy bloqueia esse acesso; o servidor usa a conexão direta (dona das tabelas) e não é afetado.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON TABLE users, habits, habit_logs, tasks, checkins, workout_exercises, sessions, session_sets, rate_limits FROM anon, authenticated;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_habits_user ON habits(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_user ON tasks(user_id, due_date);
CREATE INDEX IF NOT EXISTS idx_workout_user ON workout_exercises(user_id, weekday);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id, date);
CREATE INDEX IF NOT EXISTS idx_session_sets_session ON session_sets(session_id);
`;
